# Generated by Django 2.2.6 on 2019-10-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191021_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_heading', models.CharField(max_length=50)),
                ('show_decription', models.CharField(max_length=300)),
                ('show_poster', models.ImageField(default='', upload_to='')),
                ('show_name', models.CharField(max_length=50)),
                ('show_date', models.DateField()),
                ('show_start_time', models.TimeField()),
                ('show_end_time', models.TimeField()),
                ('show_artists', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='shows',
        ),
    ]
