# Generated by Django 2.2.6 on 2019-10-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191021_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='show_heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_heading', models.CharField(max_length=50)),
                ('show_decription', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_decription',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_heading',
        ),
    ]
