# Generated by Django 2.2.6 on 2019-10-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20191021_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist_wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(default='', upload_to='')),
                ('position', models.CharField(max_length=60)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='features_gallay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_line', models.CharField(max_length=60)),
                ('features_img', models.ImageField(default='', upload_to='')),
                ('click_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='home_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_tagline', models.CharField(max_length=50)),
                ('features_gallay_tagline', models.CharField(max_length=50)),
                ('pakage_tagline', models.CharField(max_length=50)),
                ('artist_wall_tagline', models.CharField(max_length=50)),
                ('about_us', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='pakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pakage_img', models.ImageField(default='', upload_to='')),
                ('pakage_name', models.CharField(max_length=60)),
                ('pakage_details', models.CharField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='show_heading',
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover_img',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='cover',
            name='cover_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
